name: PR Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Install Node.js
        run: pnpm env use --global 24
        shell: bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: build types
        run: pnpm run build:types

      - name: Lint
        run: pnpm run lint

      - name: Format check
        run: pnpm run fmt -- --check .

      - name: Run tests
        run: pnpm test
